# Generated by Django 3.2.6 on 2021-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanagement',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
    ]
